Add test module
MuhammadAbdullah191/personality-test pull request #1
Opened 2023-03-14 13:13 UTC by MuhammadAbdullah191

- added functionality for admin to add question and their options
- added functionality for regular user will be able to take personality-test
- added functionality of dynamic screens for personality test where user will be able to navigate through questions one by one

2023-03-14 16:27 UTC, husnainrazadevsinc requested changes
I have given feedback. Please check 👍

2023-03-14 16:27 UTC, husnainrazadevsinc commented on app/controllers/admin/questions_controller.rb
> +      4.times { @question.options.build }
Please use Global constant "NO_OF_OPTIONS" instead of 4 here

2023-03-14 16:27 UTC, husnainrazadevsinc commented on app/views/admin/questions/_form.html.erb
> +        <% end %>
I think there is no need to display these errors here in the form, the piece of code for flash in application.html.erb file should be enough, please check

2023-03-14 16:27 UTC, husnainrazadevsinc commented on app/views/home/index.html.erb
> +          <%= radio_button_tag("question_#{question.id}", option.id) %> <%=
please make a helper for that string

2023-03-14 16:27 UTC, husnainrazadevsinc commented on app/views/home/index.html.erb
> +</div>
spacing issues... please check

2023-03-14 16:27 UTC, husnainrazadevsinc commented on app/views/home/index.html.erb
> +</script>
kindly add this script code in a separate javascript file

2023-03-14 16:27 UTC, husnainrazadevsinc commented on app/views/layouts/application.html.erb
> +<% end %>
please make a partial for it

2023-03-14 16:27 UTC, husnainrazadevsinc commented on config/routes.rb
> +  end
please try use resourceful routes

2023-03-14 16:27 UTC, husnainrazadevsinc commented on app/controllers/home_controller.rb
> +    end
please put this check in another private method

2023-03-14 16:27 UTC, husnainrazadevsinc commented on app/controllers/home_controller.rb
> +      result = if option_type == 'introvert'
please use enum helpers here instead of comparing strings.

2023-03-15 07:18 UTC, MuhammadAbdullah191 commented on app/controllers/admin/questions_controller.rb
> +      4.times { @question.options.build }
sure

2023-03-15 07:18 UTC, MuhammadAbdullah191 commented on app/views/admin/questions/_form.html.erb
> +        <% end %>
noted

2023-03-15 07:18 UTC, MuhammadAbdullah191 commented on app/views/home/index.html.erb
> +          <%= radio_button_tag("question_#{question.id}", option.id) %> <%=
done

2023-03-15 07:18 UTC, MuhammadAbdullah191 commented on app/views/home/index.html.erb
> +</div>
sure

2023-03-15 07:18 UTC, MuhammadAbdullah191 commented on app/views/home/index.html.erb
> +</script>
noted

2023-03-15 07:18 UTC, MuhammadAbdullah191 commented on app/views/layouts/application.html.erb
> +<% end %>
done

2023-03-15 07:18 UTC, MuhammadAbdullah191 commented on config/routes.rb
> +  end
noted

2023-03-15 07:19 UTC, MuhammadAbdullah191 commented on app/controllers/home_controller.rb
> +    end
sure

2023-03-15 07:19 UTC, MuhammadAbdullah191 commented on app/controllers/home_controller.rb
> +      result = if option_type == 'introvert'
done

2023-03-15 08:58 UTC, husnainrazadevsinc requested changes
Suggested some changes. Please check

2023-03-15 08:58 UTC, husnainrazadevsinc commented on app/controllers/admin/questions_controller.rb
> +      render :new
please render error status along with error messages

2023-03-15 08:58 UTC, husnainrazadevsinc commented on app/controllers/admin/questions_controller.rb
> +      render :edit
same as above!

2023-03-15 08:58 UTC, husnainrazadevsinc commented on app/helpers/home_helper.rb
> +	end
spacing issues

2023-03-15 08:58 UTC, husnainrazadevsinc commented on app/javascript/packs/dynamic_form.js
> +	});
spacing issues

2023-03-15 08:58 UTC, husnainrazadevsinc commented on app/views/home/index.html.erb
> +<%= javascript_pack_tag 'dynamic_form' %>
why did you use javascript tag?
please require the required js file in the application.js file

2023-03-15 10:01 UTC, MuhammadAbdullah191 commented on app/helpers/home_helper.rb
> +	end
there is no spacing issue on my side, it might be due to something else, let me check

2023-03-15 10:06 UTC, MuhammadAbdullah191 commented on app/views/home/index.html.erb
> +<%= javascript_pack_tag 'dynamic_form' %>
ok, noted

2023-03-15 12:25 UTC, husnainrazadevsinc commented on app/javascript/packs/dynamic_form.js
> +			if (count === checkedAnswers) {
I think there is some issue with your tab spacing

2023-03-15 13:42 UTC, merged